FROM python:3.6
RUN pip install --no-cache-dir statsmodels bokeh pandas numpy pycountry xlrd scikit-learn sqlalchemy ibm-db ibm-db-sa psycopg2
RUN pip install sklearn-contrib-py-earth
WORKDIR /app/cookiecutter/static
COPY cookiecutter/static .
WORKDIR /app/cookiecutter/templates
COPY cookiecutter/templates/index.html .
WORKDIR /app/data
WORKDIR /app/cookiecutter
COPY cookiecutter/main.py .
WORKDIR /app
ENTRYPOINT bokeh serve cookiecutter --allow-websocket-origin="*" --address 0.0.0.0
