FROM python:3.8-slim
RUN pip install --no-cache-dir statsmodels bokeh pandas numpy pycountry xlrd
WORKDIR /app/cookiecutter
COPY cookiecutter/main.py .
WORKDIR /app/cookiecutter/static
COPY cookiecutter/static .
WORKDIR /app/cookiecutter/templates
COPY cookiecutter/templates/index.html .
RUN mkdir -p /app/data
WORKDIR /app
ENTRYPOINT bokeh serve cookiecutter --allow-websocket-origin="*" --address 0.0.0.0
