# util functions

def mapping(ltla):
        ltla_to_utla = {'Bury': 'Bury',
         'Hartlepool': 'Hartlepool',
         'Manchester': 'Manchester',
         'Oldham': 'Oldham',
         'Middlesbrough': 'Middlesbrough',
         'Redcar and Cleveland': 'Redcar and Cleveland',
         'Rochdale': 'Rochdale',
         'Salford': 'Salford',
         'Stockton-on-Tees': 'Stockton-on-Tees',
         'Stockport': 'Stockport',
         'Tameside': 'Tameside',
         'Darlington': 'Darlington',
         'Halton': 'Halton',
         'Trafford': 'Trafford',
         'Wigan': 'Wigan',
         'Warrington': 'Warrington',
         'Knowsley': 'Knowsley',
         'Liverpool': 'Liverpool',
         'St. Helens': 'St. Helens',
         'Blackburn with Darwen': 'Blackburn with Darwen',
         'Blackpool': 'Blackpool',
         'Sefton': 'Sefton',
         'Wirral': 'Wirral',
         'Kingston upon Hull, City of': 'Kingston upon Hull, City of',
         'East Riding of Yorkshire': 'East Riding of Yorkshire',
         'Barnsley': 'Barnsley',
         'Doncaster': 'Doncaster',
         'North East Lincolnshire': 'North East Lincolnshire',
         'North Lincolnshire': 'North Lincolnshire',
         'Rotherham': 'Rotherham',
         'York': 'York',
         'Derby': 'Derby',
         'Sheffield': 'Sheffield',
         'Newcastle upon Tyne': 'Newcastle upon Tyne',
         'Leicester': 'Leicester',
         'North Tyneside': 'North Tyneside',
         'South Tyneside': 'South Tyneside',
         'Rutland': 'Rutland',
         'Nottingham': 'Nottingham',
         'Sunderland': 'Sunderland',
         'Birmingham': 'Birmingham',
         'Herefordshire, County of': 'Herefordshire, County of',
         'Telford and Wrekin': 'Telford and Wrekin',
         'Coventry': 'Coventry',
         'Dudley': 'Dudley',
         'Stoke-on-Trent': 'Stoke-on-Trent',
         'Bath and North East Somerset': 'Bath and North East Somerset',
         'Sandwell': 'Sandwell',
         'Solihull': 'Solihull',
         'Bristol, City of': 'Bristol, City of',
         'North Somerset': 'North Somerset',
         'Walsall': 'Walsall',
         'Wolverhampton': 'Wolverhampton',
         'South Gloucestershire': 'South Gloucestershire',
         'Plymouth': 'Plymouth',
         'Bradford': 'Bradford',
         'Calderdale': 'Calderdale',
         'Torbay': 'Torbay',
         'Swindon': 'Swindon',
         'Kirklees': 'Kirklees',
         'Leeds': 'Leeds',
         'Peterborough': 'Peterborough',
         'Luton': 'Luton',
         'Wakefield': 'Wakefield',
         'Gateshead': 'Gateshead',
         'Southend-on-Sea': 'Southend-on-Sea',
         'Thurrock': 'Thurrock',
         'City of London': 'City of London',
         'Barking and Dagenham': 'Barking and Dagenham',
         'Medway': 'Medway',
         'Bracknell Forest': 'Bracknell Forest',
         'Barnet': 'Barnet',
         'Bexley': 'Bexley',
         'West Berkshire': 'West Berkshire',
         'Brent': 'Brent',
         'Reading': 'Reading',
         'Bromley': 'Bromley',
         'Slough': 'Slough',
         'Camden': 'Camden',
         'Windsor and Maidenhead': 'Windsor and Maidenhead',
         'Croydon': 'Croydon',
         'Wokingham': 'Wokingham',
         'Ealing': 'Ealing',
         'Milton Keynes': 'Milton Keynes',
         'Enfield': 'Enfield',
         'Brighton and Hove': 'Brighton and Hove',
         'Greenwich': 'Greenwich',
         'Portsmouth': 'Portsmouth',
         'Hackney': 'Hackney',
         'Southampton': 'Southampton',
         'Hammersmith and Fulham': 'Hammersmith and Fulham',
         'Isle of Wight': 'Isle of Wight',
         'Haringey': 'Haringey',
         'County Durham': 'County Durham',
         'Harrow': 'Harrow',
         'Cheshire East': 'Cheshire East',
         'Havering': 'Havering',
         'Cheshire West and Chester': 'Cheshire West and Chester',
         'Hillingdon': 'Hillingdon',
         'Shropshire': 'Shropshire',
         'Hounslow': 'Hounslow',
         'Cornwall': 'Cornwall',
         'Islington': 'Islington',
         'Isles of Scilly': 'Isles of Scilly',
         'Kensington and Chelsea': 'Kensington and Chelsea',
         'Wiltshire': 'Wiltshire',
         'Bedford': 'Bedford',
         'Central Bedfordshire': 'Central Bedfordshire',
         'Northumberland': 'Northumberland',
         'Bournemouth, Christchurch and Poole': 'Bournemouth, Christchurch and Poole',
         'Dorset': 'Dorset',
         'Bolton': 'Bolton',
         'Kingston upon Thames': 'Kingston upon Thames',
         'Lambeth': 'Lambeth',
         'Melton': 'Leicestershire',
         'North West Leicestershire': 'Leicestershire',
         'Oadby and Wigston': 'Leicestershire',
         'Boston': 'Lincolnshire',
         'East Lindsey': 'Lincolnshire',
         'Lincoln': 'Lincolnshire',
         'North Kesteven': 'Lincolnshire',
         'South Holland': 'Lincolnshire',
         'South Kesteven': 'Lincolnshire',
         'West Lindsey': 'Lincolnshire',
         'Breckland': 'Norfolk',
         'Broadland': 'Norfolk',
         'Great Yarmouth': 'Norfolk',
         "King's Lynn and West Norfolk": 'Norfolk',
         'North Norfolk': 'Norfolk',
         'Norwich': 'Norfolk',
         'South Norfolk': 'Norfolk',
         'Corby': 'Northamptonshire',
         'Daventry': 'Northamptonshire',
         'East Northamptonshire': 'Northamptonshire',
         'Kettering': 'Northamptonshire',
         'Northampton': 'Northamptonshire',
         'South Northamptonshire': 'Northamptonshire',
         'Wellingborough': 'Northamptonshire',
         'Craven': 'North Yorkshire',
         'Hambleton': 'North Yorkshire',
         'Harrogate': 'North Yorkshire',
         'Richmondshire': 'North Yorkshire',
         'Ryedale': 'North Yorkshire',
         'Scarborough': 'North Yorkshire',
         'Selby': 'North Yorkshire',
         'Ashfield': 'Nottinghamshire',
         'Bassetlaw': 'Nottinghamshire',
         'Broxtowe': 'Nottinghamshire',
         'Gedling': 'Nottinghamshire',
         'Mansfield': 'Nottinghamshire',
         'Newark and Sherwood': 'Nottinghamshire',
         'Rushcliffe': 'Nottinghamshire',
         'Cherwell': 'Oxfordshire',
         'Oxford': 'Oxfordshire',
         'South Oxfordshire': 'Oxfordshire',
         'Vale of White Horse': 'Oxfordshire',
         'West Oxfordshire': 'Oxfordshire',
         'Mendip': 'Somerset',
         'Sedgemoor': 'Somerset',
         'South Somerset': 'Somerset',
         'Somerset West and Taunton': 'Somerset',
         'Cannock Chase': 'Staffordshire',
         'East Staffordshire': 'Staffordshire',
         'Lichfield': 'Staffordshire',
         'Newcastle-under-Lyme': 'Staffordshire',
         'South Staffordshire': 'Staffordshire',
         'Stafford': 'Staffordshire',
         'Staffordshire Moorlands': 'Staffordshire',
         'Tamworth': 'Staffordshire',
         'Babergh': 'Suffolk',
         'Ipswich': 'Suffolk',
         'Mid Suffolk': 'Suffolk',
         'Tendring': 'Essex',
         'East Suffolk': 'Suffolk',
         'Uttlesford': 'Essex',
         'West Suffolk': 'Suffolk',
         'Cheltenham': 'Gloucestershire',
         'Elmbridge': 'Surrey',
         'Cotswold': 'Gloucestershire',
         'Epsom and Ewell': 'Surrey',
         'Forest of Dean': 'Gloucestershire',
         'Guildford': 'Surrey',
         'Gloucester': 'Gloucestershire',
         'Mole Valley': 'Surrey',
         'Stroud': 'Gloucestershire',
         'Reigate and Banstead': 'Surrey',
         'Tewkesbury': 'Gloucestershire',
         'Runnymede': 'Surrey',
         'Basingstoke and Deane': 'Hampshire',
         'Spelthorne': 'Surrey',
         'East Hampshire': 'Hampshire',
         'Surrey Heath': 'Surrey',
         'Eastleigh': 'Hampshire',
         'Tandridge': 'Surrey',
         'Fareham': 'Hampshire',
         'Waverley': 'Surrey',
         'Gosport': 'Hampshire',
         'Woking': 'Surrey',
         'Hart': 'Hampshire',
         'North Warwickshire': 'Warwickshire',
         'Havant': 'Hampshire',
         'Nuneaton and Bedworth': 'Warwickshire',
         'New Forest': 'Hampshire',
         'Rugby': 'Warwickshire',
         'Rushmoor': 'Hampshire',
         'Test Valley': 'Hampshire',
         'Winchester': 'Hampshire',
         'Broxbourne': 'Hertfordshire',
         'Dacorum': 'Hertfordshire',
         'Hertsmere': 'Hertfordshire',
         'North Hertfordshire': 'Hertfordshire',
         'Three Rivers': 'Hertfordshire',
         'Watford': 'Hertfordshire',
         'St Albans': 'Hertfordshire',
         'Welwyn Hatfield': 'Hertfordshire',
         'East Hertfordshire': 'Hertfordshire',
         'Stevenage': 'Hertfordshire',
         'Ashford': 'Kent',
         'Canterbury': 'Kent',
         'Dartford': 'Kent',
         'Dover': 'Kent',
         'Gravesham': 'Kent',
         'Maidstone': 'Kent',
         'Sevenoaks': 'Kent',
         'Folkestone and Hythe': 'Kent',
         'Swale': 'Kent',
         'Thanet': 'Kent',
         'Tonbridge and Malling': 'Kent',
         'Tunbridge Wells': 'Kent',
         'Burnley': 'Lancashire',
         'Chorley': 'Lancashire',
         'Fylde': 'Lancashire',
         'Hyndburn': 'Lancashire',
         'Lancaster': 'Lancashire',
         'Pendle': 'Lancashire',
         'Preston': 'Lancashire',
         'Ribble Valley': 'Lancashire',
         'Rossendale': 'Lancashire',
         'South Ribble': 'Lancashire',
         'West Lancashire': 'Lancashire',
         'Wyre': 'Lancashire',
         'Blaby': 'Leicestershire',
         'Charnwood': 'Leicestershire',
         'Harborough': 'Leicestershire',
         'Hinckley and Bosworth': 'Leicestershire',
         'Stratford-on-Avon': 'Warwickshire',
         'Warwick': 'Warwickshire',
         'Adur': 'West Sussex',
         'Arun': 'West Sussex',
         'Chichester': 'West Sussex',
         'Crawley': 'West Sussex',
         'Horsham': 'West Sussex',
         'Mid Sussex': 'West Sussex',
         'Worthing': 'West Sussex',
         'Bromsgrove': 'Worcestershire',
         'Malvern Hills': 'Worcestershire',
         'Redditch': 'Worcestershire',
         'Worcester': 'Worcestershire',
         'Wychavon': 'Worcestershire',
         'Wyre Forest': 'Worcestershire',
         'Isle of Anglesey': 'Isle of Anglesey',
         'Gwynedd': 'Gwynedd',
         'Conwy': 'Conwy',
         'Denbighshire': 'Denbighshire',
         'Flintshire': 'Flintshire',
         'Wrexham': 'Wrexham',
         'Ceredigion': 'Ceredigion',
         'Pembrokeshire': 'Pembrokeshire',
         'Carmarthenshire': 'Carmarthenshire',
         'Swansea': 'Swansea',
         'Neath Port Talbot': 'Neath Port Talbot',
         'Bridgend': 'Bridgend',
         'Vale of Glamorgan': 'Vale of Glamorgan',
         'Cardiff': 'Cardiff',
         'Rhondda Cynon Taf': 'Rhondda Cynon Taf',
         'Caerphilly': 'Caerphilly',
         'Blaenau Gwent': 'Blaenau Gwent',
         'Torfaen': 'Torfaen',
         'Monmouthshire': 'Monmouthshire',
         'Newport': 'Newport',
         'Powys': 'Powys',
         'Merthyr Tydfil': 'Merthyr Tydfil',
         'Lewisham': 'Lewisham',
         'Merton': 'Merton',
         'Newham': 'Newham',
         'Redbridge': 'Redbridge',
         'Richmond upon Thames': 'Richmond upon Thames',
         'Southwark': 'Southwark',
         'Sutton': 'Sutton',
         'Tower Hamlets': 'Tower Hamlets',
         'Waltham Forest': 'Waltham Forest',
         'Wandsworth': 'Wandsworth',
         'Westminster': 'Westminster',
         'Aylesbury Vale': 'Buckinghamshire',
         'Chiltern': 'Buckinghamshire',
         'South Bucks': 'Buckinghamshire',
         'Wycombe': 'Buckinghamshire',
         'Cambridge': 'Cambridgeshire',
         'East Cambridgeshire': 'Cambridgeshire',
         'Fenland': 'Cambridgeshire',
         'Huntingdonshire': 'Cambridgeshire',
         'South Cambridgeshire': 'Cambridgeshire',
         'Allerdale': 'Cumbria',
         'Barrow-in-Furness': 'Cumbria',
         'Carlisle': 'Cumbria',
         'Copeland': 'Cumbria',
         'Eden': 'Cumbria',
         'South Lakeland': 'Cumbria',
         'Amber Valley': 'Derbyshire',
         'Bolsover': 'Derbyshire',
         'Chesterfield': 'Derbyshire',
         'Derbyshire Dales': 'Derbyshire',
         'Erewash': 'Derbyshire',
         'High Peak': 'Derbyshire',
         'North East Derbyshire': 'Derbyshire',
         'South Derbyshire': 'Derbyshire',
         'East Devon': 'Devon',
         'Exeter': 'Devon',
         'Mid Devon': 'Devon',
         'North Devon': 'Devon',
         'South Hams': 'Devon',
         'Teignbridge': 'Devon',
         'Torridge': 'Devon',
         'West Devon': 'Devon',
         'Eastbourne': 'East Sussex',
         'Hastings': 'East Sussex',
         'Lewes': 'East Sussex',
         'Rother': 'East Sussex',
         'Wealden': 'East Sussex',
         'Basildon': 'Essex',
         'Braintree': 'Essex',
         'Brentwood': 'Essex',
         'Castle Point': 'Essex',
         'Chelmsford': 'Essex',
         'Colchester': 'Essex',
         'Epping Forest': 'Essex',
         'Harlow': 'Essex',
         'Maldon': 'Essex',
         'Rochford': 'Essex'}
        return ltla_to_utla[ltla]        